image:
  file: .gitpod.Dockerfile

ports:
  - port: 8545
    name: Blockchain RPC
    description: Hardhat Ethereum Node
    visibility: public
  - port: 5173
    name: Frontend
    description: Vite Development Server
    onOpen: open-browser

tasks:
  - name: Install Dependencies
    init: npm install
    command: echo "✅ Ready! Run 'npx hardhat node' to start blockchain"

vscode:
  extensions:
    - NomicFoundation.hardhat-solidity
    - dbaeumer.vscode-eslint

